# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T13:51:41+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, confloat, conint, constr


class AddressId(
    RootModel[
        constr(
            pattern=r'ADID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            min_length=40,
            max_length=40,
        )
    ]
):
    root: constr(
        pattern=r'ADID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        min_length=40,
        max_length=40,
    )


class AmiId(
    RootModel[
        constr(
            pattern=r'(ami-[0-9a-f]{8})|(ami-[0-9a-f]{17})',
            min_length=12,
            max_length=21,
        )
    ]
):
    root: constr(
        pattern=r'(ami-[0-9a-f]{8})|(ami-[0-9a-f]{17})', min_length=12, max_length=21
    )


class Boolean(RootModel[bool]):
    root: bool


class CancelClusterResult(BaseModel):
    pass


class CancelJobResult(BaseModel):
    pass


class ClusterId(
    RootModel[
        constr(
            pattern=r'CID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            min_length=39,
            max_length=39,
        )
    ]
):
    root: constr(
        pattern=r'CID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        min_length=39,
        max_length=39,
    )


class ClusterLimitExceededException(RootModel[Any]):
    root: Any


class ClusterState(Enum):
    AwaitingQuorum = 'AwaitingQuorum'
    Pending = 'Pending'
    InUse = 'InUse'
    Complete = 'Complete'
    Cancelled = 'Cancelled'


class ConflictException(RootModel[Any]):
    root: Any


class DescribeAddressRequest(BaseModel):
    AddressId_1: AddressId = Field(..., alias='AddressId')


class DescribeClusterRequest(BaseModel):
    ClusterId_1: ClusterId = Field(..., alias='ClusterId')


class DeviceServiceName(Enum):
    NFS_ON_DEVICE_SERVICE = 'NFS_ON_DEVICE_SERVICE'
    S3_ON_DEVICE_SERVICE = 'S3_ON_DEVICE_SERVICE'


class Ec2RequestFailedException(RootModel[Any]):
    root: Any


class GSTIN(
    RootModel[
        constr(
            pattern=r'\d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}',
            min_length=15,
            max_length=15,
        )
    ]
):
    root: constr(
        pattern=r'\d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}',
        min_length=15,
        max_length=15,
    )


class GetSnowballUsageRequest(BaseModel):
    pass


class INDTaxDocuments(BaseModel):
    GSTIN_1: Optional[GSTIN] = Field(None, alias='GSTIN')


class InitialClusterSize(RootModel[conint(ge=0, le=16)]):
    root: conint(ge=0, le=16)


class Integer(RootModel[int]):
    root: int


class InvalidAddressException(RootModel[Any]):
    root: Any


class InvalidInputCombinationException(RootModel[Any]):
    root: Any


class InvalidJobStateException(RootModel[Any]):
    root: Any


class InvalidNextTokenException(RootModel[Any]):
    root: Any


class InvalidResourceException(RootModel[Any]):
    root: Any


class JavaBoolean(RootModel[bool]):
    root: bool


class JobId(
    RootModel[
        constr(
            pattern=r'(M|J)ID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            min_length=39,
            max_length=39,
        )
    ]
):
    root: constr(
        pattern=r'(M|J)ID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        min_length=39,
        max_length=39,
    )


class JobState(Enum):
    New = 'New'
    PreparingAppliance = 'PreparingAppliance'
    PreparingShipment = 'PreparingShipment'
    InTransitToCustomer = 'InTransitToCustomer'
    WithCustomer = 'WithCustomer'
    InTransitToAWS = 'InTransitToAWS'
    WithAWSSortingFacility = 'WithAWSSortingFacility'
    WithAWS = 'WithAWS'
    InProgress = 'InProgress'
    Complete = 'Complete'
    Cancelled = 'Cancelled'
    Listing = 'Listing'
    Pending = 'Pending'


class JobStateList(RootModel[List[JobState]]):
    root: List[JobState]


class JobType(Enum):
    IMPORT = 'IMPORT'
    EXPORT = 'EXPORT'
    LOCAL_USE = 'LOCAL_USE'


class KMSRequestFailedException(RootModel[Any]):
    root: Any


class KmsKeyARN(
    RootModel[constr(pattern=r'arn:aws.*:kms:.*:[0-9]{12}:key/.*', max_length=255)]
):
    root: constr(pattern=r'arn:aws.*:kms:.*:[0-9]{12}:key/.*', max_length=255)


class ListLimit(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class Long(RootModel[int]):
    root: int


class LongTermPricingAssociatedJobIdList(RootModel[List[JobId]]):
    root: List[JobId]


class LongTermPricingId(
    RootModel[
        constr(
            pattern=r'LTPID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            min_length=41,
            max_length=41,
        )
    ]
):
    root: constr(
        pattern=r'LTPID[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        min_length=41,
        max_length=41,
    )


class LongTermPricingIdList(RootModel[List[LongTermPricingId]]):
    root: List[LongTermPricingId]


class LongTermPricingType(Enum):
    OneYear = 'OneYear'
    ThreeYear = 'ThreeYear'
    OneMonth = 'OneMonth'


class NodeFaultTolerance(RootModel[conint(ge=1, le=4)]):
    root: conint(ge=1, le=4)


class RemoteManagement(Enum):
    INSTALLED_ONLY = 'INSTALLED_ONLY'
    INSTALLED_AUTOSTART = 'INSTALLED_AUTOSTART'


class ResourceARN(RootModel[constr(pattern=r'arn:aws.*:*', max_length=255)]):
    root: constr(pattern=r'arn:aws.*:*', max_length=255)


class ReturnShippingLabelAlreadyExistsException(RootModel[Any]):
    root: Any


class RoleARN(
    RootModel[constr(pattern=r'arn:aws.*:iam::[0-9]{12}:role/.*', max_length=255)]
):
    root: constr(pattern=r'arn:aws.*:iam::[0-9]{12}:role/.*', max_length=255)


class S3StorageLimit(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)


class ServiceName(Enum):
    KUBERNETES = 'KUBERNETES'
    EKS_ANYWHERE = 'EKS_ANYWHERE'


class ServiceSize(RootModel[conint(ge=3, le=16)]):
    root: conint(ge=3, le=16)


class ShipmentState(Enum):
    RECEIVED = 'RECEIVED'
    RETURNED = 'RETURNED'


class ShippingLabelStatus(Enum):
    InProgress = 'InProgress'
    TimedOut = 'TimedOut'
    Succeeded = 'Succeeded'
    Failed = 'Failed'


class ShippingOption(Enum):
    SECOND_DAY = 'SECOND_DAY'
    NEXT_DAY = 'NEXT_DAY'
    EXPRESS = 'EXPRESS'
    STANDARD = 'STANDARD'


class SnowballCapacity(Enum):
    T50 = 'T50'
    T80 = 'T80'
    T100 = 'T100'
    T42 = 'T42'
    T98 = 'T98'
    T8 = 'T8'
    T14 = 'T14'
    T32 = 'T32'
    NoPreference = 'NoPreference'
    T240 = 'T240'


class SnowballType(Enum):
    STANDARD = 'STANDARD'
    EDGE = 'EDGE'
    EDGE_C = 'EDGE_C'
    EDGE_CG = 'EDGE_CG'
    EDGE_S = 'EDGE_S'
    SNC1_HDD = 'SNC1_HDD'
    SNC1_SSD = 'SNC1_SSD'
    V3_5C = 'V3_5C'
    V3_5S = 'V3_5S'


class SnsTopicARN(
    RootModel[constr(pattern=r'arn:aws.*:sns:.*:[0-9]{12}:.*', max_length=255)]
):
    root: constr(pattern=r'arn:aws.*:sns:.*:[0-9]{12}:.*', max_length=255)


class StorageLimit(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class StorageUnit(Enum):
    TB = 'TB'


class String(RootModel[constr(pattern=r'.*', min_length=1, max_length=1024)]):
    root: constr(pattern=r'.*', min_length=1, max_length=1024)


class TGWOnDeviceServiceConfiguration(BaseModel):
    StorageLimit_1: Optional[StorageLimit] = Field(None, alias='StorageLimit')
    StorageUnit_1: Optional[StorageUnit] = Field(None, alias='StorageUnit')


class TaxDocuments(BaseModel):
    IND: Optional[INDTaxDocuments] = None


class Timestamp(RootModel[datetime]):
    root: datetime


class TransferOption(Enum):
    IMPORT = 'IMPORT'
    EXPORT = 'EXPORT'
    LOCAL_USE = 'LOCAL_USE'


class UnsupportedAddressException(RootModel[Any]):
    root: Any


class UpdateClusterResult(BaseModel):
    pass


class UpdateJobResult(BaseModel):
    pass


class UpdateJobShipmentStateRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')
    ShipmentState_1: ShipmentState = Field(..., alias='ShipmentState')


class UpdateJobShipmentStateResult(BaseModel):
    pass


class UpdateLongTermPricingRequest(BaseModel):
    IsLongTermPricingAutoRenew: Optional[JavaBoolean] = None
    LongTermPricingId_1: LongTermPricingId = Field(..., alias='LongTermPricingId')
    ReplacementJob: Optional[JobId] = None


class UpdateLongTermPricingResult(BaseModel):
    pass


class WirelessConnection(BaseModel):
    IsWifiEnabled: Optional[Boolean] = None


class XAmzTarget(Enum):
    AWSIESnowballJobManagementService_CancelCluster = (
        'AWSIESnowballJobManagementService.CancelCluster'
    )


class XAmzTarget1(Enum):
    AWSIESnowballJobManagementService_CancelJob = (
        'AWSIESnowballJobManagementService.CancelJob'
    )


class XAmzTarget2(Enum):
    AWSIESnowballJobManagementService_CreateAddress = (
        'AWSIESnowballJobManagementService.CreateAddress'
    )


class XAmzTarget3(Enum):
    AWSIESnowballJobManagementService_CreateCluster = (
        'AWSIESnowballJobManagementService.CreateCluster'
    )


class XAmzTarget4(Enum):
    AWSIESnowballJobManagementService_CreateJob = (
        'AWSIESnowballJobManagementService.CreateJob'
    )


class XAmzTarget5(Enum):
    AWSIESnowballJobManagementService_CreateLongTermPricing = (
        'AWSIESnowballJobManagementService.CreateLongTermPricing'
    )


class XAmzTarget6(Enum):
    AWSIESnowballJobManagementService_CreateReturnShippingLabel = (
        'AWSIESnowballJobManagementService.CreateReturnShippingLabel'
    )


class XAmzTarget7(Enum):
    AWSIESnowballJobManagementService_DescribeAddress = (
        'AWSIESnowballJobManagementService.DescribeAddress'
    )


class XAmzTarget8(Enum):
    AWSIESnowballJobManagementService_DescribeAddresses = (
        'AWSIESnowballJobManagementService.DescribeAddresses'
    )


class XAmzTarget9(Enum):
    AWSIESnowballJobManagementService_DescribeCluster = (
        'AWSIESnowballJobManagementService.DescribeCluster'
    )


class XAmzTarget10(Enum):
    AWSIESnowballJobManagementService_DescribeJob = (
        'AWSIESnowballJobManagementService.DescribeJob'
    )


class XAmzTarget11(Enum):
    AWSIESnowballJobManagementService_DescribeReturnShippingLabel = (
        'AWSIESnowballJobManagementService.DescribeReturnShippingLabel'
    )


class XAmzTarget12(Enum):
    AWSIESnowballJobManagementService_GetJobManifest = (
        'AWSIESnowballJobManagementService.GetJobManifest'
    )


class XAmzTarget13(Enum):
    AWSIESnowballJobManagementService_GetJobUnlockCode = (
        'AWSIESnowballJobManagementService.GetJobUnlockCode'
    )


class XAmzTarget14(Enum):
    AWSIESnowballJobManagementService_GetSnowballUsage = (
        'AWSIESnowballJobManagementService.GetSnowballUsage'
    )


class XAmzTarget15(Enum):
    AWSIESnowballJobManagementService_GetSoftwareUpdates = (
        'AWSIESnowballJobManagementService.GetSoftwareUpdates'
    )


class XAmzTarget16(Enum):
    AWSIESnowballJobManagementService_ListClusterJobs = (
        'AWSIESnowballJobManagementService.ListClusterJobs'
    )


class XAmzTarget17(Enum):
    AWSIESnowballJobManagementService_ListClusters = (
        'AWSIESnowballJobManagementService.ListClusters'
    )


class XAmzTarget18(Enum):
    AWSIESnowballJobManagementService_ListCompatibleImages = (
        'AWSIESnowballJobManagementService.ListCompatibleImages'
    )


class XAmzTarget19(Enum):
    AWSIESnowballJobManagementService_ListJobs = (
        'AWSIESnowballJobManagementService.ListJobs'
    )


class XAmzTarget20(Enum):
    AWSIESnowballJobManagementService_ListLongTermPricing = (
        'AWSIESnowballJobManagementService.ListLongTermPricing'
    )


class XAmzTarget21(Enum):
    AWSIESnowballJobManagementService_ListServiceVersions = (
        'AWSIESnowballJobManagementService.ListServiceVersions'
    )


class XAmzTarget22(Enum):
    AWSIESnowballJobManagementService_UpdateCluster = (
        'AWSIESnowballJobManagementService.UpdateCluster'
    )


class XAmzTarget23(Enum):
    AWSIESnowballJobManagementService_UpdateJob = (
        'AWSIESnowballJobManagementService.UpdateJob'
    )


class XAmzTarget24(Enum):
    AWSIESnowballJobManagementService_UpdateJobShipmentState = (
        'AWSIESnowballJobManagementService.UpdateJobShipmentState'
    )


class XAmzTarget25(Enum):
    AWSIESnowballJobManagementService_UpdateLongTermPricing = (
        'AWSIESnowballJobManagementService.UpdateLongTermPricing'
    )


class Address(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    City: Optional[String] = None
    Company: Optional[String] = None
    Country: Optional[String] = None
    IsRestricted: Optional[Boolean] = None
    Landmark: Optional[String] = None
    Name: Optional[String] = None
    PhoneNumber: Optional[String] = None
    PostalCode: Optional[String] = None
    PrefectureOrDistrict: Optional[String] = None
    StateOrProvince: Optional[String] = None
    Street1: Optional[String] = None
    Street2: Optional[String] = None
    Street3: Optional[String] = None


class AddressList(RootModel[List[Address]]):
    root: List[Address]


class CancelClusterRequest(BaseModel):
    ClusterId_1: ClusterId = Field(..., alias='ClusterId')


class CancelJobRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class ClusterListEntry(BaseModel):
    ClusterId: Optional[String] = None
    ClusterState_1: Optional[ClusterState] = Field(None, alias='ClusterState')
    CreationDate: Optional[Timestamp] = None
    Description: Optional[String] = None


class ClusterListEntryList(RootModel[List[ClusterListEntry]]):
    root: List[ClusterListEntry]


class CompatibleImage(BaseModel):
    AmiId: Optional[String] = None
    Name: Optional[String] = None


class CompatibleImageList(RootModel[List[CompatibleImage]]):
    root: List[CompatibleImage]


class CreateAddressRequest(BaseModel):
    Address_1: Address = Field(..., alias='Address')


class CreateAddressResult(BaseModel):
    AddressId: Optional[String] = None


class CreateJobResult(BaseModel):
    JobId_1: Optional[JobId] = Field(None, alias='JobId')


class CreateLongTermPricingRequest(BaseModel):
    IsLongTermPricingAutoRenew: Optional[JavaBoolean] = None
    LongTermPricingType_1: LongTermPricingType = Field(..., alias='LongTermPricingType')
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')


class CreateLongTermPricingResult(BaseModel):
    LongTermPricingId_1: Optional[LongTermPricingId] = Field(
        None, alias='LongTermPricingId'
    )


class CreateReturnShippingLabelRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')


class CreateReturnShippingLabelResult(BaseModel):
    Status: Optional[ShippingLabelStatus] = None


class DataTransfer(BaseModel):
    BytesTransferred: Optional[Long] = None
    ObjectsTransferred: Optional[Long] = None
    TotalBytes: Optional[Long] = None
    TotalObjects: Optional[Long] = None


class DescribeAddressResult(BaseModel):
    Address_1: Optional[Address] = Field(None, alias='Address')


class DescribeAddressesRequest(BaseModel):
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class DescribeAddressesResult(BaseModel):
    Addresses: Optional[AddressList] = None
    NextToken: Optional[String] = None


class DescribeJobRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class DescribeReturnShippingLabelRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class DescribeReturnShippingLabelResult(BaseModel):
    ExpirationDate: Optional[Timestamp] = None
    ReturnShippingLabelURI: Optional[String] = None
    Status: Optional[ShippingLabelStatus] = None


class EKSOnDeviceServiceConfiguration(BaseModel):
    EKSAnywhereVersion: Optional[String] = None
    KubernetesVersion: Optional[String] = None


class Ec2AmiResource(BaseModel):
    AmiId_1: AmiId = Field(..., alias='AmiId')
    SnowballAmiId: Optional[String] = None


class Ec2AmiResourceList(RootModel[List[Ec2AmiResource]]):
    root: List[Ec2AmiResource]


class EventTriggerDefinition(BaseModel):
    EventResourceARN: Optional[ResourceARN] = None


class EventTriggerDefinitionList(RootModel[List[EventTriggerDefinition]]):
    root: List[EventTriggerDefinition]


class GetJobManifestRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class GetJobManifestResult(BaseModel):
    ManifestURI: Optional[String] = None


class GetJobUnlockCodeRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class GetJobUnlockCodeResult(BaseModel):
    UnlockCode: Optional[String] = None


class GetSnowballUsageResult(BaseModel):
    SnowballLimit: Optional[Integer] = None
    SnowballsInUse: Optional[Integer] = None


class GetSoftwareUpdatesRequest(BaseModel):
    JobId_1: JobId = Field(..., alias='JobId')


class GetSoftwareUpdatesResult(BaseModel):
    UpdatesURI: Optional[String] = None


class JobListEntry(BaseModel):
    CreationDate: Optional[Timestamp] = None
    Description: Optional[String] = None
    IsMaster: Optional[Boolean] = None
    JobId: Optional[String] = None
    JobState_1: Optional[JobState] = Field(None, alias='JobState')
    JobType_1: Optional[JobType] = Field(None, alias='JobType')
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')


class JobListEntryList(RootModel[List[JobListEntry]]):
    root: List[JobListEntry]


class JobLogs(BaseModel):
    JobCompletionReportURI: Optional[String] = None
    JobFailureLogURI: Optional[String] = None
    JobSuccessLogURI: Optional[String] = None


class KeyRange(BaseModel):
    BeginMarker: Optional[String] = None
    EndMarker: Optional[String] = None


class LambdaResource(BaseModel):
    EventTriggers: Optional[EventTriggerDefinitionList] = None
    LambdaArn: Optional[ResourceARN] = None


class LambdaResourceList(RootModel[List[LambdaResource]]):
    root: List[LambdaResource]


class ListClusterJobsRequest(BaseModel):
    ClusterId_1: ClusterId = Field(..., alias='ClusterId')
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class ListClusterJobsResult(BaseModel):
    JobListEntries: Optional[JobListEntryList] = None
    NextToken: Optional[String] = None


class ListClustersRequest(BaseModel):
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class ListClustersResult(BaseModel):
    ClusterListEntries: Optional[ClusterListEntryList] = None
    NextToken: Optional[String] = None


class ListCompatibleImagesRequest(BaseModel):
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class ListCompatibleImagesResult(BaseModel):
    CompatibleImages: Optional[CompatibleImageList] = None
    NextToken: Optional[String] = None


class ListJobsRequest(BaseModel):
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class ListJobsResult(BaseModel):
    JobListEntries: Optional[JobListEntryList] = None
    NextToken: Optional[String] = None


class ListLongTermPricingRequest(BaseModel):
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None


class LongTermPricingListEntry(BaseModel):
    CurrentActiveJob: Optional[JobId] = None
    IsLongTermPricingAutoRenew: Optional[JavaBoolean] = None
    JobIds: Optional[LongTermPricingAssociatedJobIdList] = None
    LongTermPricingEndDate: Optional[Timestamp] = None
    LongTermPricingId_1: Optional[LongTermPricingId] = Field(
        None, alias='LongTermPricingId'
    )
    LongTermPricingStartDate: Optional[Timestamp] = None
    LongTermPricingStatus: Optional[String] = None
    LongTermPricingType_1: Optional[LongTermPricingType] = Field(
        None, alias='LongTermPricingType'
    )
    ReplacementJob: Optional[JobId] = None
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')


class NFSOnDeviceServiceConfiguration(BaseModel):
    StorageLimit_1: Optional[StorageLimit] = Field(None, alias='StorageLimit')
    StorageUnit_1: Optional[StorageUnit] = Field(None, alias='StorageUnit')


class Notification(BaseModel):
    JobStatesToNotify: Optional[JobStateList] = None
    NotifyAll: Optional[Boolean] = None
    SnsTopicARN_1: Optional[SnsTopicARN] = Field(None, alias='SnsTopicARN')


class S3OnDeviceServiceConfiguration(BaseModel):
    FaultTolerance: Optional[NodeFaultTolerance] = None
    ServiceSize_1: Optional[ServiceSize] = Field(None, alias='ServiceSize')
    StorageLimit: Optional[S3StorageLimit] = None
    StorageUnit_1: Optional[StorageUnit] = Field(None, alias='StorageUnit')


class ServiceVersion(BaseModel):
    Version: Optional[String] = None


class ServiceVersionList(RootModel[List[ServiceVersion]]):
    root: List[ServiceVersion]


class Shipment(BaseModel):
    Status: Optional[String] = None
    TrackingNumber: Optional[String] = None


class ShippingDetails(BaseModel):
    InboundShipment: Optional[Shipment] = None
    OutboundShipment: Optional[Shipment] = None
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')


class SnowconeDeviceConfiguration(BaseModel):
    WirelessConnection_1: Optional[WirelessConnection] = Field(
        None, alias='WirelessConnection'
    )


class TargetOnDeviceService(BaseModel):
    ServiceName: Optional[DeviceServiceName] = None
    TransferOption_1: Optional[TransferOption] = Field(None, alias='TransferOption')


class TargetOnDeviceServiceList(RootModel[List[TargetOnDeviceService]]):
    root: List[TargetOnDeviceService]


class CreateClusterResult(BaseModel):
    ClusterId_1: Optional[ClusterId] = Field(None, alias='ClusterId')
    JobListEntries: Optional[JobListEntryList] = None


class DependentService(BaseModel):
    ServiceName_1: Optional[ServiceName] = Field(None, alias='ServiceName')
    ServiceVersion_1: Optional[ServiceVersion] = Field(None, alias='ServiceVersion')


class DependentServiceList(RootModel[List[DependentService]]):
    root: List[DependentService]


class DeviceConfiguration(BaseModel):
    SnowconeDeviceConfiguration_1: Optional[SnowconeDeviceConfiguration] = Field(
        None, alias='SnowconeDeviceConfiguration'
    )


class ListServiceVersionsRequest(BaseModel):
    DependentServices: Optional[DependentServiceList] = None
    MaxResults: Optional[ListLimit] = None
    NextToken: Optional[String] = None
    ServiceName_1: ServiceName = Field(..., alias='ServiceName')


class ListServiceVersionsResult(BaseModel):
    DependentServices: Optional[DependentServiceList] = None
    NextToken: Optional[String] = None
    ServiceName_1: ServiceName = Field(..., alias='ServiceName')
    ServiceVersions: ServiceVersionList


class LongTermPricingEntryList(RootModel[List[LongTermPricingListEntry]]):
    root: List[LongTermPricingListEntry]


class OnDeviceServiceConfiguration(BaseModel):
    EKSOnDeviceService: Optional[EKSOnDeviceServiceConfiguration] = None
    NFSOnDeviceService: Optional[NFSOnDeviceServiceConfiguration] = None
    S3OnDeviceService: Optional[S3OnDeviceServiceConfiguration] = None
    TGWOnDeviceService: Optional[TGWOnDeviceServiceConfiguration] = None


class S3Resource(BaseModel):
    BucketArn: Optional[ResourceARN] = None
    KeyRange_1: Optional[KeyRange] = Field(None, alias='KeyRange')
    TargetOnDeviceServices: Optional[TargetOnDeviceServiceList] = None


class S3ResourceList(RootModel[List[S3Resource]]):
    root: List[S3Resource]


class JobResource(BaseModel):
    Ec2AmiResources: Optional[Ec2AmiResourceList] = None
    LambdaResources: Optional[LambdaResourceList] = None
    S3Resources: Optional[S3ResourceList] = None


class ListLongTermPricingResult(BaseModel):
    LongTermPricingEntries: Optional[LongTermPricingEntryList] = None
    NextToken: Optional[String] = None


class UpdateClusterRequest(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    ClusterId_1: ClusterId = Field(..., alias='ClusterId')
    Description: Optional[String] = None
    ForwardingAddressId: Optional[AddressId] = None
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')


class UpdateJobRequest(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    Description: Optional[String] = None
    ForwardingAddressId: Optional[AddressId] = None
    JobId_1: JobId = Field(..., alias='JobId')
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')
    SnowballCapacityPreference: Optional[SnowballCapacity] = None


class ClusterMetadata(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    ClusterId: Optional[String] = None
    ClusterState_1: Optional[ClusterState] = Field(None, alias='ClusterState')
    CreationDate: Optional[Timestamp] = None
    Description: Optional[String] = None
    ForwardingAddressId: Optional[AddressId] = None
    JobType_1: Optional[JobType] = Field(None, alias='JobType')
    KmsKeyARN_1: Optional[KmsKeyARN] = Field(None, alias='KmsKeyARN')
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')
    TaxDocuments_1: Optional[TaxDocuments] = Field(None, alias='TaxDocuments')


class CreateClusterRequest(BaseModel):
    AddressId_1: AddressId = Field(..., alias='AddressId')
    Description: Optional[String] = None
    ForceCreateJobs: Optional[Boolean] = None
    ForwardingAddressId: Optional[AddressId] = None
    InitialClusterSize_1: Optional[InitialClusterSize] = Field(
        None, alias='InitialClusterSize'
    )
    JobType_1: JobType = Field(..., alias='JobType')
    KmsKeyARN_1: Optional[KmsKeyARN] = Field(None, alias='KmsKeyARN')
    LongTermPricingIds: Optional[LongTermPricingIdList] = None
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    RemoteManagement_1: Optional[RemoteManagement] = Field(
        None, alias='RemoteManagement'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingOption_1: ShippingOption = Field(..., alias='ShippingOption')
    SnowballCapacityPreference: Optional[SnowballCapacity] = None
    SnowballType_1: SnowballType = Field(..., alias='SnowballType')
    TaxDocuments_1: Optional[TaxDocuments] = Field(None, alias='TaxDocuments')


class CreateJobRequest(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    ClusterId_1: Optional[ClusterId] = Field(None, alias='ClusterId')
    Description: Optional[String] = None
    DeviceConfiguration_1: Optional[DeviceConfiguration] = Field(
        None, alias='DeviceConfiguration'
    )
    ForwardingAddressId: Optional[AddressId] = None
    JobType_1: Optional[JobType] = Field(None, alias='JobType')
    KmsKeyARN_1: Optional[KmsKeyARN] = Field(None, alias='KmsKeyARN')
    LongTermPricingId_1: Optional[LongTermPricingId] = Field(
        None, alias='LongTermPricingId'
    )
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    RemoteManagement_1: Optional[RemoteManagement] = Field(
        None, alias='RemoteManagement'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingOption_1: Optional[ShippingOption] = Field(None, alias='ShippingOption')
    SnowballCapacityPreference: Optional[SnowballCapacity] = None
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')
    TaxDocuments_1: Optional[TaxDocuments] = Field(None, alias='TaxDocuments')


class DescribeClusterResult(BaseModel):
    ClusterMetadata_1: Optional[ClusterMetadata] = Field(None, alias='ClusterMetadata')


class JobMetadata(BaseModel):
    AddressId_1: Optional[AddressId] = Field(None, alias='AddressId')
    ClusterId: Optional[String] = None
    CreationDate: Optional[Timestamp] = None
    DataTransferProgress: Optional[DataTransfer] = None
    Description: Optional[String] = None
    DeviceConfiguration_1: Optional[DeviceConfiguration] = Field(
        None, alias='DeviceConfiguration'
    )
    ForwardingAddressId: Optional[AddressId] = None
    JobId: Optional[String] = None
    JobLogInfo: Optional[JobLogs] = None
    JobState_1: Optional[JobState] = Field(None, alias='JobState')
    JobType_1: Optional[JobType] = Field(None, alias='JobType')
    KmsKeyARN_1: Optional[KmsKeyARN] = Field(None, alias='KmsKeyARN')
    LongTermPricingId_1: Optional[LongTermPricingId] = Field(
        None, alias='LongTermPricingId'
    )
    Notification_1: Optional[Notification] = Field(None, alias='Notification')
    OnDeviceServiceConfiguration_1: Optional[OnDeviceServiceConfiguration] = Field(
        None, alias='OnDeviceServiceConfiguration'
    )
    RemoteManagement_1: Optional[RemoteManagement] = Field(
        None, alias='RemoteManagement'
    )
    Resources: Optional[JobResource] = None
    RoleARN_1: Optional[RoleARN] = Field(None, alias='RoleARN')
    ShippingDetails_1: Optional[ShippingDetails] = Field(None, alias='ShippingDetails')
    SnowballCapacityPreference: Optional[SnowballCapacity] = None
    SnowballType_1: Optional[SnowballType] = Field(None, alias='SnowballType')
    TaxDocuments_1: Optional[TaxDocuments] = Field(None, alias='TaxDocuments')


class JobMetadataList(RootModel[List[JobMetadata]]):
    root: List[JobMetadata]


class DescribeJobResult(BaseModel):
    JobMetadata_1: Optional[JobMetadata] = Field(None, alias='JobMetadata')
    SubJobMetadata: Optional[JobMetadataList] = None
